language: cpp
compiler: gcc
dist: cosmic

before_install:
  # C++17
  # sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-7 libboost-all-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target all
  - cmake --build . --target test
